---
title: "Reporte de Deuda de Gobiernos locales"
author: "BEST"
date: "Realizado el `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: journal
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Un título interesante

Aqui algo de texto

```{r configuracion_inicial,echo=FALSE,comment=F,warning=FALSE,message=FALSE}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)

setwd("D:/ABCN/Github/MDv01sesion2_parte-practica/2 Deuda de los gobiernos locales")
bd2020 <-  readxl::read_xls("Reporte_Deuda_GRGL_30042020.xls",sheet = "Resumen",skip = 18)
bd2020 <- bd2020[1:11,6:9]
names(bd2020) <- c("acreedor","USD","PEN","porcentaje")
bd2020[1,1] <- "MEF"
bd2020[,-1]=sapply(bd2020[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2020$periodo="2020-04-30"          

bd2019 <-  readxl::read_xls("Reporte_Deuda_GRGL_31122019.xls",sheet = "Resumen",skip = 18)
bd2019 <- bd2019[1:11,6:9]
names(bd2019) <- c("acreedor","USD","PEN","porcentaje")
bd2019[1,1] <- "MEF"
bd2019[,-1]<-sapply(bd2019[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2019$periodo<-"2019-12-31"          

bd2018 <-  readxl::read_xls("Reporte_Deuda_GRGL_31122018.xls",sheet = "Resumen",skip = 18)
bd2018 <- bd2018[1:11,6:9]
names(bd2018) <- c("acreedor","USD","PEN","porcentaje")
bd2018[1,1] <- "MEF"
bd2018[,-1] <- sapply(bd2018[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2018$periodo <- "2018-12-31"     
bd2018 <- bd2018[complete.cases(bd2018$USD),]


bd2017 <-  readxl::read_xls("Reporte_Deuda_GRGL_31122017.xls",sheet = "Resumen",skip = 18)
bd2017 <- bd2017[1:14,6:9]
names(bd2017) <- c("acreedor","USD","PEN","porcentaje")
bd2017[1,1] <- "MEF"
bd2017[,-1]<-sapply(bd2017[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2017$periodo<-"2017-12-31"    

bd2016 <-  readxl::read_xls("Reporte_Deuda_GRGL_31122016.xls",sheet = "Resumen Cuadros",skip = 19)
bd2016 <- bd2016[1:15,7:10]
names(bd2016) <- c("acreedor","USD","PEN","porcentaje")
bd2016[1,1] <- "MEF"
bd2016[,-1]<-sapply(bd2016[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2016$periodo<-"2016-12-31"    

bd2015 <-  readxl::read_xls("Reporte_Deuda_GRGL_31122015.xls",sheet = "Resumen Cuadros",skip = 19)
bd2015 <- bd2015[1:15,7:10]
names(bd2015) <- c("acreedor","USD","PEN","porcentaje")
bd2015[1,1] <- "MEF"
bd2015[,-1]<-sapply(bd2015[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2015$periodo<-"2015-12-31"   

bd2014 <-  readxl::read_xls("Reporte_Deuda_GRGL_311214.xls",sheet = "Resumen Cuadros",skip = 19)
bd2014 <- bd2014[1:16,7:10]
names(bd2014) <- c("acreedor","USD","PEN","porcentaje")
bd2014[1,1] <- "MEF"
bd2014[,-1]<-sapply(bd2014[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2014$periodo<-"2014-12-31"   

bd2013 <-  readxl::read_xls("Reporte_Deuda_GRGL_311213.xls",sheet = "Resumen Cuadros",skip = 19)
bd2013 <- bd2013[1:16,7:10]
names(bd2013) <- c("acreedor","USD","PEN","porcentaje")
bd2013[1,1] <- "MEF"
bd2013[,-1]<-sapply(bd2013[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2013$periodo<-"2013-12-31"   

bd2012 <-  readxl::read_xls("reporte_deuda_GRGL_31122012.xls",sheet = "Resumen Cuadros",skip = 19)
bd2012 <- bd2012[1:15,7:10]
names(bd2012) <- c("acreedor","USD","PEN","porcentaje")
bd2012[1,1] <- "MEF"
bd2012[,-1]<-sapply(bd2012[,-1],function(x) round(as.numeric(as.character(x)),2))
bd2012$periodo<-"2012-12-31"   
bd2012 <- bd2012[complete.cases(bd2012$USD),]

# unimos las bd

bd <- rbind(bd2020,bd2019)
bd <- rbind(bd,bd2018)
bd <- rbind(bd,bd2017)
bd <- rbind(bd,bd2016)
bd <- rbind(bd,bd2015)
bd <- rbind(bd,bd2014)
bd <- rbind(bd,bd2013)
bd <- rbind(bd,bd2012)
bd<-bd %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco Financiero", "Banco Pichincha")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Financiero", "Banco Pichincha")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco del Crédito del Perú", "BCP")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco de Crédito del Perú", "BCP")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. de Crédito", "BCP")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco de Crédito", "BCP")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA B. Continental", "BBVA")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA Banco Continental", "BBVA")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco Internacional del Perú", "Interbank")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Internacional del Perú", "Interbank")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Banco de la Nación", "BN")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. de la Nación", "BN")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Scotiabank", "Scotiabank")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Scotiabank Perú", "Scotiabank")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. de Comercio", "Banco de Comercio")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Comercio", "Banco de Comercio")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA Banco Continental - Sindicado", "Sindicado")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA Continental - Bco. Scotiabank - Sindicado", "Sindicado")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA, Scotia Y BCP Sindicado", "Sindicado")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="BBVA Continental-Scotiabank-Sindic.", "Sindicado")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Caja Metropolitano de Lima", "Caja Metropolitana de Lima")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Wiese Sudameris", "Banco Wiese Sudameris")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Agropecuario", "Banco Agropecuario")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Interamericano de Desarrollo (BID)", "Banco Interamericano de Desarrollo (BID)")) %>%
        mutate(acreedor=replace(acreedor, acreedor=="Bco. Internacional de  Reconstrucción y Fomento (BIRF)", "Banco Internacional de Reconstrucción y Fomento (BIRF)")) %>%  
        as.data.frame()

bd <- bd %>% select(periodo,acreedor,PEN)
bd$periodo=as.Date(bd$periodo)
bd<-bd %>% mutate(PEN = case_when(periodo == "2012-12-31"  ~ PEN/1000,
                              TRUE ~ PEN)) # casewhen es una funcion de dplyr
```

## Grafico general

```{r grafico_general, echo=FALSE,comment=F,warning=FALSE,message=FALSE,fig.height=10}


grafico1<-ggplot(bd, aes(x = periodo, y = PEN)) + 
  geom_line(aes(color = acreedor), size = 1) +
  theme_minimal()

# grafico1
ggplotly(grafico1) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
```


## Práctica dirigida

### Pregunta 1

Grafica solo MEF con Sindicado

```{r grafico_1, echo=FALSE,comment=F,warning=FALSE,message=FALSE,fig.height=10}
bd_grafico1 <- bd  %>% filter(acreedor %in% c("Sindicado","MEF"))

grafico1<-ggplot(bd_grafico1, aes(x = periodo, y = PEN)) + 
  geom_line(aes(color = acreedor), size = 1) +
  theme_minimal()

# grafico1
ggplotly(grafico1) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
```
## Tarea

### Pregunta 1

Grafica solo BCP, BBVA, Interbank, Scotiabank y Sindicado; añade nombres a los ejes X y Y. Añadir título, subtítulo. y cualquier cosa que se vea mejor el gráfico!

